In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
# Load the dataset
url = "https://raw.githubusercontent.com/Anuj020/CsvFiles/main/fifa21_male2.csv"
dataset = pd.read_csv(url)

C:\Users\Anuj\AppData\Local\Temp\ipykernel_9184\1696729654.py:3: DtypeWarning: Columns (78) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv(url)

In [3]:
fifa = dataset.head(1000)

fifa.drop(["ID","Nationality","Club","BOV","BP","Position","Player Photo","Club Logo","Flag Photo","Team & Contract","foot","Growth","Joined","Loan Date End","Value","Wage","Contract","Attacking","Crossing","Finishing",
          "Heading Accuracy","Short Passing","Volleys","Skill","Dribbling","Curve","FK Accuracy","Long Passing","Ball Control","Movement",
          "Acceleration","Sprint Speed","Agility","Reactions","Balance","Power","Shot Power","Jumping","Long Shots",
          "Mentality","Aggression","Interceptions","Positioning","Vision","Penalties","Composure","Defending","Marking","Standing Tackle",
          "Sliding Tackle","Goalkeeping","GK Diving","GK Handling","GK Kicking","GK Positioning","GK Reflexes","Base Stats",
          "W/F","SM","A/W","D/W","IR","PAC","SHO","PAS","DRI","DEF","PHY","Hits","LS","ST","RS","LW","LF","CF","RF","RW","LAM","CAM","RAM","LM","LCM","CM","RCM","RM","LWB","LDM","CDM","RDM",
          "RWB","LB","LCB","CB","RCB","RB","GK","Gender"], axis=1, inplace=True)

fifa.shape

f1 =fifa.columns
f1

C:\Users\Anuj\AppData\Local\Temp\ipykernel_9184\293494081.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa.drop(["ID","Nationality","Club","BOV","BP","Position","Player Photo","Club Logo","Flag Photo","Team & Contract","foot","Growth","Joined","Loan Date End","Value","Wage","Contract","Attacking","Crossing","Finishing",

Index(['Name', 'Age', 'OVA', 'POT', 'Height', 'Weight', 'Release Clause',
       'Stamina', 'Strength', 'Total Stats'],
      dtype='object')

In [4]:
cat_col = ['Name', 'Age', 'OVA', 'POT', 'Height', 'Weight', 'Release Clause', 'Strength', 'Total Stats']

get_dummy = pd.get_dummies(fifa,columns=cat_col ,drop_first= True)

get_dummy

,Stamina,Name_A. Alc√°raz,Name_A. Aquilani,Name_A. Arshavin,Name_A. Baptiste,Name_A. Barzagli,Name_A. Baumjohann,Name_A. Bellinghausen,Name_A. Bennett,Name_A. Boruc,...,Total Stats_2170,Total Stats_2173,Total Stats_2180,Total Stats_2181,Total Stats_2192,Total Stats_2205,Total Stats_2207,Total Stats_2221,Total Stats_2231,Total Stats_2258
0,69,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,64,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,29,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,51,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,58,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,33,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
996,34,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
997,52,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
998,77,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
999,35,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
from sklearn.metrics import accuracy_score
input_features = get_dummy.drop("Stamina",axis=1)  # Add the desired input features
output_labels = get_dummy["Stamina"]  # Add the desired output labels


# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(input_features, output_labels, test_size=0.2, random_state=42)

# Build the ANN model
model = keras.Sequential([
    layers.Dense(30, activation="sigmoid", input_shape=(X_train.shape[1],)),
    layers.Dense(15, activation="sigmoid"),
    layers.Dense(1)  # The number of neurons depends on the number of output labels
])

# Compile the model
model.compile(optimizer="adam", loss="mean_squared_error")

# Train the model
model.fit(X_train, y_train)

# Evaluate the model
loss= model.evaluate(X_test,y_test)
print("Test loss:", loss)

25/25 [==============================] - 1s 2ms/step - loss: 3318.7302
7/7 [==============================] - 0s 1ms/step - loss: 3093.5425
Test loss: 3093.54248046875